### ISSUE TITLE
百度小程序图片路径问题

### ISSUE THREAD

**Issue by jing2si** [guless/mpx-webpack-plugin#2]
examples 中的例子，app.json 中的图片路径 build 后没办法识别，路径如下：
`"iconPath": "/images\ticket_4bf11d.png",`，将  `\`  改成 `/` 就好了，能否修正下。

**Comment by Samlv9** [comment]
目前版本 windows 中很多路径都有问题，当时做的时候没有考虑 window 的兼容性。。。
如果你有时间话，可否帮忙提个 PR？

**Comment by Samlv9** [comment]
路径问题已经修复了，试试最新版本 [v1.0.10]
